import {
  Recad,
  RecadRoot,
  General,
  Shape,
  RoomType,
  MeasuringSurfaceType,
  SensorType,
  ShortInfoType,
  ShortInfoSensorType,
  LuminaireType,
  GeometryRefType,
  ResultType,
  WallType,
  MaterialRef,
  ObjectType,
  SceneType,
  StructureType,
  ShapeType,
  WallElementType,
  GroundElementType,
  CeilingElementType,
  CalcSettingsType,
  SceneResultType,
  GeoInfoType,
  MeshDefType,
  SensorDefType,
  LuminaireDefType,
  UtilisationType,
  ProjectInfoType,
  MaterialDef,
  BooleanObjectType,
  SceneInfoDef,
  LocationDef,
  MeshType,
  FreeSurfaceType,
  StoreyInfoType,
} from './recadTypes';

export type RecadConstructor = new (props?: any) => unknown;

export const RecadTypeMap = {
  [Recad.className]: Recad,
  [RecadRoot.className]: RecadRoot,
  [General.className]: General,
  [Shape.className]: Shape,
  [RoomType.className]: RoomType,
  [MeasuringSurfaceType.className]: MeasuringSurfaceType,
  [SensorType.className]: SensorType,
  [ShortInfoType.className]: ShortInfoType,
  [ShortInfoSensorType.className]: ShortInfoSensorType,
  [LuminaireType.className]: LuminaireType,
  [GeometryRefType.className]: GeometryRefType,
  [ResultType.className]: ResultType,
  [WallType.className]: WallType,
  [MaterialRef.className]: MaterialRef,
  [ObjectType.className]: ObjectType,
  [SceneType.className]: SceneType,
  [StructureType.className]: StructureType,
  [ShapeType.className]: ShapeType,
  [WallElementType.className]: WallElementType,
  [GroundElementType.className]: GroundElementType,
  [CeilingElementType.className]: CeilingElementType,
  [CalcSettingsType.className]: CalcSettingsType,
  [SceneResultType.className]: SceneResultType,
  [GeoInfoType.className]: GeoInfoType,
  [MeshDefType.className]: MeshDefType,
  [SensorDefType.className]: SensorDefType,
  [LuminaireDefType.className]: LuminaireDefType,
  [UtilisationType.className]: UtilisationType,
  [ProjectInfoType.className]: ProjectInfoType,
  [MaterialDef.className]: MaterialDef,
  [BooleanObjectType.className]: BooleanObjectType,
  [SceneInfoDef.className]: SceneInfoDef,
  [LocationDef.className]: LocationDef,
  [MeshType.className]: MeshType,
  [FreeSurfaceType.className]: FreeSurfaceType,
  [StoreyInfoType.className]: StoreyInfoType,
} as const satisfies Record<string, RecadConstructor>;

export type RecadClassName = keyof typeof RecadTypeMap;
